/*
	Experimental boiling water reactor
	This reactor utilises its own components that interact with fuel rods in a specific pattern. Generation is based on the layout of the vents, heat shields and control rods.


	Reactor has 6 by 6 grid for layout.

	Overall working:
	1. Through UI, user will put types of components into the slots, which then will be put inside the machine based on the pattern and cords.alist
	2. Each tick when reactor will be online, will calculate the total heat generated by the fuel rods, put them into the surrounding vents or heatshields, which is either stored or slowly dissipated by vents, and the total heat vented by the vents.
	3. The more heat reactor has accumulated, the more damage the rods will take, and how much power it will make. Notice, each component has its own integrity. If it reaches zero, they will break, and reactor might go unstable

	Components will have different tier, for different types of fuel. Aka, enriched plutonium, MOX, and Unstable Bluespace fuel.
	Higher tier fuel will generate more heat, and more power, but also will damage the rods faster, and might overwhelm the vents.

*/

/obj/machinery/reactor
	name = "Micron Control Systems GA37W Experimental Nuclear Reactor"
	desc = "A massive experimental reactor made by Micron Control Systems."
	icon = 'modular_zzplurt/code/modules/power/NC/reactor96x96.dmi'
	icon_state = "idle"
	bound_x = 96
	bound_y = 96
	layer = OBJ_LAYER

	/// Grid width of the reactor in tiles.
	var/width = 6
	/// Grid height of the reactor in tiles.
	var/height = 6
	/// The grid of reactor cells. [x][y] format = component path.
	var/list/grid = list()
	/// Current temperature of the reactor.
	var/temperature = 0
	/// Maximum temperature of the reactor before meltdown.
	var/max_temperature = 1000
	/// The last power output of the reactor.
	var/last_power_output = 0
	/// The power grid this reactor is connected to.
	var/datum/powernet/powernet/power_grid = null

	/// Are we online or offline?
	var/reactor_status = REACTOR_OFFLINE


/obj/machinery/reactor/Initialize()
	. = ..()
	grid = list()
	grid.len = width * height

/obj/machinery/reactor/proc/grid_index(x, y)
	if(x < 1 || y < 1 || x > width || y > height)
		return null
	return x + (y - 1) * width

/obj/machinery/reactor/proc/check_for_errors()
	var/last_reactor_error = ""
	return last_reactor_error

/obj/machinery/reactor/proc/activate()
	src.process()
	START_PROCESSING(1)
	reactor_status = REACTOR_ONLINE
	return TRUE


/obj/machinery/reactor/proc/process(5 SECONDS)
	. = ..()
	if(reactor_status == REACTOR_OFFLINE)
		reactor_status = REACTOR_OFFLINE
		return

	// ----- Reset linkage containers on components -----
	for(var/cell_index = 1; cell_index <= grid.len; cell_index++)
		if(grid[cell_index]){
			grid[cell_index].linked_shields = list()
			grid[cell_index].linked_fuel_rods = list()
		}

	// ----- Link fuel rods to adjacent heat shields -----
	for(var/pos_x = 1; pos_x <= width; pos_x++)
		for(var/pos_y = 1; pos_y <= height; pos_y++){
			var/current_index = grid_index(pos_x, pos_y)
			if(!current_index) continue
			var/component = grid[current_index]
			if(!component) continue

			if(istype(component, /obj/item/reactor_component/fuel_rod)){
				// check the four cardinal neighbors
				for(var/off_x = -1; off_x <= 1; off_x++)
					for(var/off_y = -1; off_y <= 1; off_y++){
						if(abs(off_x) + abs(off_y) != 1) continue
						var/neighbor_x = pos_x + off_x
						var/neighbor_y = pos_y + off_y
						var/neighbor_index = grid_index(neighbor_x, neighbor_y)
						if(!neighbor_index) continue
						var/neighbor_component = grid[neighbor_index]
						if(!neighbor_component) continue
						if(istype(neighbor_component, /obj/item/reactor_component/heat_shield)){
							if(!component.linked_shields) component.linked_shields = list()
							var/exists = FALSE
							for(var/_shield in component.linked_shields)
								if(_shield == neighbor_component) { exists = TRUE break }
							if(!exists) component.linked_shields[component.linked_shields.len + 1] = neighbor_component

							if(!neighbor_component.linked_fuel_rods) neighbor_component.linked_fuel_rods = list()
							var/already = FALSE
							for(var/_rod in neighbor_component.linked_fuel_rods)
								if(_rod == component) { already = TRUE break }
							if(!already) neighbor_component.linked_fuel_rods[neighbor_component.linked_fuel_rods.len + 1] = component
						}
					}
			}
		}

	// ----- Heat transfer, venting and damage -----
	for(var/pos_x = 1; pos_x <= width; pos_x++)
		for(var/pos_y = 1; pos_y <= height; pos_y++){
			var/current_index = grid_index(pos_x, pos_y)
			if(!current_index) continue
			var/component = grid[current_index]
			if(!component) continue

			// --- Fuel rods: produce heat, distribute to linked shields or core ---
			if(istype(component, /obj/item/reactor_component/fuel_rod)){
				var/heat_val = 0
				if(component.heat_generation) heat_val = component.heat_generation
				else if(component.heat_gen) heat_val = component.heat_gen
				var/efficiency = component.efficiency ? component.efficiency : 1.0
				var/link_count = component.linked_shields ? component.linked_shields.len : 0
				if(link_count > 0){
					var/share = (heat_val * efficiency) / link_count
					for(var/_shield in component.linked_shields)
						if(_shield) _shield.heat_stored = (_shield.heat_stored ?? 0) + share
				}else{
					temperature += heat_val * efficiency
				}

				// integrity decay for rod
				if(!component.integrity) component.integrity = ROD_INTEGRITY_BASE
				var/decay = max(ROD_INTEGRITY_MIN_DECAY, (heat_val * ROD_DECAY_MULT))
				component.integrity -= decay
				if(component.integrity <= 0){
					grid[current_index] = null
					qdel(component)
				}
			}

			// --- Heat shields: pass heat to vents and take damage if overloaded ---
			if(istype(component, /obj/item/reactor_component/heat_shield)){
				component.heat_stored = component.heat_stored ?? 0
				var/adjacent_vents = list()
				for(var/off_x = -1; off_x <= 1; off_x++)
					for(var/off_y = -1; off_y <= 1; off_y++){
						if(abs(off_x) + abs(off_y) != 1) continue
						var/neighbor_x = pos_x + off_x
						var/neighbor_y = pos_y + off_y
						var/neighbor_index = grid_index(neighbor_x, neighbor_y)
						if(!neighbor_index) continue
						var/neighbor_component = grid[neighbor_index]
						if(!neighbor_component) continue
						if(istype(neighbor_component, /obj/item/reactor_component/vent))
							adjacent_vents[adjacent_vents.len + 1] = neighbor_component
					}

				if(adjacent_vents.len > 0 && component.heat_stored > 0){
					var/transfer_total = component.heat_stored * SHIELD_TO_VENT_TRANSFER_RATIO
					var/per_vent = transfer_total / adjacent_vents.len
					for(var/_vent in adjacent_vents)
						_vent.heat_stored = (_vent.heat_stored ?? 0) + per_vent
					component.heat_stored -= transfer_total
				}

				var/shield_capacity = component.heat_capacity ? component.heat_capacity : SHIELD_DEFAULT_CAPACITY
				if(component.heat_stored > shield_capacity){
					if(!component.integrity) component.integrity = SHIELD_INTEGRITY_BASE
					component.integrity -= (component.heat_stored - shield_capacity) * 0.01
					if(component.integrity <= 0){
						var/remove_index = grid_index(pos_x, pos_y)
						if(remove_index) grid[remove_index] = null
						qdel(component)
					}
				}
			}

			// --- Vents: dissipate heat and break if overloaded ---
			if(istype(component, /obj/item/reactor_component/vent)){
				component.heat_stored = component.heat_stored ?? 0
				var/cool_rate = VENT_DEFAULT_COOL
				if(component.heat_gen) cool_rate = abs(component.heat_gen)
				var/removed = min(component.heat_stored, cool_rate)
				component.heat_stored -= removed

				var/vent_capacity = component.heat_capacity ? component.heat_capacity : VENT_DEFAULT_CAPACITY
				if(component.heat_stored > vent_capacity){
					if(!component.integrity) component.integrity = VENT_INTEGRITY_BASE
					component.integrity -= (component.heat_stored - vent_capacity) * 0.02
					if(component.integrity <= 0){
						var/remove_index = grid_index(pos_x, pos_y)
						if(remove_index) grid[remove_index] = null
						qdel(component)
					}
				}
			}
		}


/obj/item/reactor_component
	/// You should not see it anyways.
	name = "Generic Reactor Component"
	icon = 'modular_skyrat/master_files/icons/mob/augmentation/mcgipc.dmi';
	var/id = null
	var/heat_gen
	var/heat_stored
	var/integrity

	/// The power output of this component.
	var/power_output = 0
	/// The heat generated by this component.
	var/heat_generation = 0
	/// The efficiency of this component (0.0 - 1.0).
	var/efficiency = 1.0

/obj/item/reactor_component/vent
	name = "Reactor Vent"
	icon_state = "robotic_l_leg"
	efficiency = 1
	heat_stored = 0
	heat_gen = -5

/obj/item/reactor_component/fuel_rod
	icon_state = "robotic_l_leg"
	name = "Fuel Rod"
	power_output = 20
	heat_generation = 10
	efficiency = 1

/obj/item/reactor_component/heat_shield
	icon_state = "robotic_l_leg"
	name = "Heat Shield"
	efficiency = 1
	heat_stored = 0

/obj/machinery/reactor/ui_interact(mob/user, datum/tgui/ui)
	. = ..()
	ui = SStgui.try_update_ui(user, src, ui)
	if(!ui)
		ui = new(user, src, "ReactorUI")
		ui.open()
		ui.set_autoupdate(FALSE)

/obj/machinery/reactor/ui_data(datum/ui_state/state)
    var/list/data = list()
    data["grid"] = grid
    data["grid_x"] = width
    data["grid_y"] = height
    data["temperature"] = temperature
    data["max_temperature"] = max_temperature
    data["reactor_status"] = reactor_status
    data["last_power_output"] = last_power_output
    return data

/obj/machinery/reactor/attackby(obj/item/weapon, mob/user, list/modifiers, list/attack_modifiers)
	if(istype(weapon, /obj/item/reactor_component))
		ui_interact(user)

/obj/machinery/reactor/ui_act(action, list/params, datum/tgui/ui, datum/ui_state/state)
	. = ..()
	switch(action)
		if("reactor")
			if(params["action"] == "click_slot")
				var/x = text2num(params["x"])
				var/y = text2num(params["y"])
				if(x && y)
					modify_slot(ui.user, x, y)
					return TRUE

/obj/machinery/reactor/proc/modify_slot(mob/user, x, y)
	var/obj/item/reactor_component/held_item = user.get_active_held_item()

	if(!held_item)
		to_chat(user, "<span class='warning'>You must be holding a reactor component.</span>")
		return FALSE

	var/index = grid_index(x, y)
	if(!index)
		return FALSE

	if(grid[index])
		to_chat(user, "<span class='warning'>That slot is already occupied.</span>")
		return FALSE

	user.dropItemToGround(held_item)
	held_item.forceMove(src)

	grid[index] = held_item
	return TRUE
