/*
	Experimental boiling water reactor
	This reactor utilises its own components that interact with fuel rods in a specific pattern. Generation is based on the layout of the vents, heat shields and control rods.


	Reactor has 6 by 6 grid for layout.

	Overall working:
	1. Through UI, user will put types of components into the slots, which then will be put inside the machine based on the pattern and cords.alist
	2. Each tick when reactor will be online, will calculate the total heat generated by the fuel rods, put them into the surrounding vents or heatshields, which is either stored or slowly dissipated by vents, and the total heat vented by the vents.
	3. The more heat reactor has accumulated, the more damage the rods will take, and how much power it will make. Notice, each component has its own integrity. If it reaches zero, they will break, and reactor might go unstable

	Components will have different tier, for different types of fuel. Aka, enriched plutonium, MOX, and Unstable Bluespace fuel.
	Higher tier fuel will generate more heat, and more power, but also will damage the rods faster, and might overwhelm the vents.

*/

/obj/machinery/reactor
	name = "Micron Control Systems GA37W Experimental Nuclear Reactor"
	desc = "A massive experimental reactor made by Micron Control Systems."
	icon = 'modular_zzplurt/code/modules/power/NC/reactor96x96.dmi'
	icon_state = "idle"
	bound_x = 96
	bound_y = 96
	layer = OBJ_LAYER

	/// Grid width of the reactor in tiles.
	var/width = 6
	/// Grid height of the reactor in tiles.
	var/height = 6
	/// The grid of reactor cells. [x][y] format = component path.
	var/list/grid = list()
	/// Current temperature of the reactor.
	var/temperature = 0
	/// Maximum temperature of the reactor before meltdown.
	var/max_temperature = 1000
	/// The last power output of the reactor.
	var/last_power_output = 0
	/// The power grid this reactor is connected to.
	var/datum/powernet/powernet/power_grid = null

	/// Are we online or offline?
	var/reactor_status = REACTOR_OFFLINE


/obj/machinery/reactor/Initialize()
	. = ..()
	grid = list()
	grid.len = width * height

/obj/machinery/reactor/proc/grid_index(x, y)
	if(x < 1 || y < 1 || x > width || y > height)
		return null
	return x + (y - 1) * width

/obj/machinery/reactor/proc/check_for_errors()
	var/last_reactor_error = ""
	return last_reactor_error

/obj/machinery/reactor/proc/activate()
	rebuild_links()
	reactor_status = REACTOR_ONLINE
	src.process()

/obj/machinery/reactor/proc/rebuild_links()
	// Reset
	for(var/obj/item/reactor_component/C in grid)
		if(!C) continue
		C.adjacent_rods = list()
		C.linked_heat_acceptors = list()
		C.linked_vents = list()

	// Scan once
	for(var/y = 1; y <= height; y++)
		for(var/x = 1; x <= width; x++)
			var/i = grid_index(x, y)
			var/obj/item/reactor_component/C = grid[i]
			if(!C) continue

			for(var/d in list(NORTH, SOUTH, EAST, WEST))
				var/nx = x + (d == EAST) - (d == WEST)
				var/ny = y + (d == NORTH) - (d == SOUTH)
				var/ni = grid_index(nx, ny)
				if(!ni) continue

				var/obj/item/reactor_component/N = grid[ni]
				if(!N) continue

				// Rod ↔ Rod
				if(istype(C, /obj/item/reactor_component/fuel_rod) && istype(N, /obj/item/reactor_component/fuel_rod))
					C.adjacent_rods += N

				// Rod → heat acceptor
				if(istype(C, /obj/item/reactor_component/fuel_rod) && !istype(N, /obj/item/reactor_component/fuel_rod))
					C.linked_heat_acceptors += N

				// Shield → vent
				if(istype(C, /obj/item/reactor_component/heat_shield) && istype(N, /obj/item/reactor_component/vent))
					C.linked_vents += N

/obj/machinery/reactor/process()
	if(reactor_status != REACTOR_ONLINE)
		return

	last_power_output = 0

	// =========================
	// FUEL RODS
	// =========================
	for(var/obj/item/reactor_component/fuel_rod/R in grid)
		if(!R) continue

		// --- Pulses (IC2 style)
		var/pulses = 1
		if(R.adjacent_rods)
			pulses += R.adjacent_rods.len

		var/heat_generated = R.base_heat_gen * pulses
		var/power_generated = R.base_power_gen * pulses

		// --- Heat distribution
		if(R.linked_heat_acceptors && R.linked_heat_acceptors.len)
			var/share = heat_generated / R.linked_heat_acceptors.len
			for(var/obj/item/reactor_component/A in R.linked_heat_acceptors)
				if(!A) continue
				A.heat_stored = (A.heat_stored || 0) + share
		else
			temperature += heat_generated

		last_power_output += power_generated

		// --- Rod damage
		R.integrity ||= ROD_INTEGRITY_BASE
		R.integrity -= max(ROD_INTEGRITY_MIN_DECAY, heat_generated * ROD_DECAY_MULT)

		if(R.integrity <= 0)
			qdel(R)

	// =========================
	// HEAT SHIELDS
	// =========================
	for(var/obj/item/reactor_component/heat_shield/S in grid)
		if(!S) continue

		S.heat_stored ||= 0

		if(S.linked_vents && S.linked_vents.len && S.heat_stored > 0)
			var/transfer = S.heat_stored * SHIELD_TO_VENT_TRANSFER_RATIO
			var/per = transfer / S.linked_vents.len

			for(var/obj/item/reactor_component/vent/V in S.linked_vents)
				if(!V) continue
				V.heat_stored = (V.heat_stored || 0) + per

			S.heat_stored -= transfer

		var/capacity = S.heat_capacity || SHIELD_DEFAULT_CAPACITY
		if(S.heat_stored > capacity)
			S.integrity ||= SHIELD_INTEGRITY_BASE
			S.integrity -= (S.heat_stored - capacity) * 0.01
			if(S.integrity <= 0)
				qdel(S)

	// =========================
	// VENTS
	// =========================
	for(var/obj/item/reactor_component/vent/V in grid)
		if(!V) continue

		V.heat_stored ||= 0

		var/cool = abs(V.cool_rate) || VENT_DEFAULT_COOL
		var/removed = min(V.heat_stored, cool)
		V.heat_stored -= removed

		var/cap = V.heat_capacity || VENT_DEFAULT_CAPACITY
		if(V.heat_stored > cap)
			V.integrity ||= VENT_INTEGRITY_BASE
			V.integrity -= (V.heat_stored - cap) * 0.02
			if(V.integrity <= 0)
				qdel(V)

	// =========================
	// CORE STATUS
	// =========================
	if(temperature >= max_temperature)
		//reactor_status = REACTOR_MELTDOWN


/obj/item/reactor_component
	name = "Generic Reactor Component"
	icon = 'modular_skyrat/master_files/icons/mob/augmentation/mcgipc.dmi'
	var/id = null

	var/heat_stored = 0
	var/integrity = 100

	var/component_type
	var/max_heat = 1000

	// Optional defaults
	var/heat_capacity = 0
	var/efficiency = 1.0

	var/list/adjacent_rods = list()
	var/list/linked_heat_acceptors = list()
	var/list/linked_vents = list()


/obj/item/reactor_component/vent
	name = "Reactor Vent"

	heat_capacity = 800
	max_heat = 1000

	var/cool_rate = 5


/obj/item/reactor_component/fuel_rod
	name = "Uranium Fuel Rod"
	max_heat = 2000

	var/base_heat_gen = 10
	var/base_power_gen = 50

	// Runtime calculated

	// Optional scaling
	var/pulse_bonus = 0.1


/obj/item/reactor_component/heat_shield
	name = "Heat Shield"
	heat_capacity = 1000
	max_heat = 1500



/obj/machinery/reactor/ui_interact(mob/user, datum/tgui/ui)
	. = ..()
	ui = SStgui.try_update_ui(user, src, ui)
	if(!ui)
		ui = new(user, src, "ReactorUI")
		ui.open()
		ui.set_autoupdate(FALSE)

/obj/machinery/reactor/ui_data(datum/ui_state/state)
    var/list/data = list()
    data["grid"] = grid
    data["grid_x"] = width
    data["grid_y"] = height
    data["temperature"] = temperature
    data["max_temperature"] = max_temperature
    data["reactor_status"] = reactor_status
    data["last_power_output"] = last_power_output
    return data

/obj/machinery/reactor/attackby(obj/item/weapon, mob/user, list/modifiers, list/attack_modifiers)
	if(istype(weapon, /obj/item/reactor_component))
		ui_interact(user)

/obj/machinery/reactor/ui_act(action, list/params, datum/tgui/ui, datum/ui_state/state)
	. = ..()
	switch(action)
		if("reactor")
			if(params["action"] == "click_slot")
				var/x = text2num(params["x"])
				var/y = text2num(params["y"])
				if(x && y)
					modify_slot(ui.user, x, y)
					return TRUE

/obj/machinery/reactor/proc/modify_slot(mob/user, x, y)
	var/obj/item/reactor_component/held_item = user.get_active_held_item()

	if(!held_item)
		to_chat(user, "<span class='warning'>You must be holding a reactor component.</span>")
		return FALSE

	var/index = grid_index(x, y)
	if(!index)
		return FALSE

	if(grid[index])
		to_chat(user, "<span class='warning'>That slot is already occupied.</span>")
		return FALSE

	user.dropItemToGround(held_item)
	held_item.forceMove(src)

	grid[index] = held_item
	return TRUE
